#!/bin/bash

JOBS=16

KERNEL_VERSION_HEAD=6
KERNEL_VERSION=$KERNEL_VERSION_HEAD.8.5
KERNEL_ARCHIVE=linux-$KERNEL_VERSION.tar.xz

GLIBC_VERSION=2.39
GLIBC_ARCHIVE=glibc-$GLIBC_VERSION.tar.xz

BUSYBOX_VERSION=1.36.1
BUSYBOX_ARCHIVE=busybox-$BUSYBOX_VERSION.tar.bz2

INIT_PATH=$(pwd)/initrd

rm -rf initrd*
mkdir -p initrd

mkdir -p archives
cd archives
    if [ ! -f $KERNEL_ARCHIVE ]; then
        wget https://mirrors.edge.kernel.org/pub/linux/kernel/v$KERNEL_VERSION_HEAD.x/$KERNEL_ARCHIVE
    fi

    if [ ! -f $GLIBC_ARCHIVE ]; then
        wget https://ftp.gnu.org/gnu/glibc/$GLIBC_ARCHIVE
    fi

    if [ ! -f $BUSYBOX_ARCHIVE ]; then
        wget https://busybox.net/downloads/$BUSYBOX_ARCHIVE
    fi
cd ..

mkdir -p src
cd src
    if [ "$1" = "kernel" ]; then
        rm -f -r linux*
        tar -xf ../archives/$KERNEL_ARCHIVE
        
        cd linux-$KERNEL_VERSION
            make defconfig
            if [ "$2" = "menu" ]; then
                make menuconfig
            fi
            make -j $JOBS || exit
            cp arch/x86/boot/bzImage ../../
        cd ..
    fi

    tar -xf ../archives/$GLIBC_ARCHIVE
    cd glibc-$GLIBC_VERSION
        mkdir build
        cd build
            ../configure --prefix=$INIT_PATH/usr
            make -j $JOBS || exit
            make install
        cd ..
    cd ..

    tar -xf ../archives/$BUSYBOX_ARCHIVE
    cd busybox-$BUSYBOX_VERSION
        make defconfig
        make -j $JOBS || exit
        make install CONFIG_PREFIX=$INIT_PATH
    cd ..
cd ..

cd initrd
    echo "#/bin/sh" > init
    echo "/bin/sh" >> init

    find . | cpio -o -H newc > ../initrd.img
cd ..
