#!/bin/bash

mkdir -p initrd
cd initrd
    mkdir -p bin dev

    cp ../src/busybox bin
    cd bin
        for cmd in $(./busybox --list); do
            ln -s /bin/busybox $cmd || exit
        done
    cd ..

    touch dev/tty
    touch dev/tty1
    touch dev/tty2
    touch dev/tty3
    touch dev/tty4

    cp -f ../SBinary/bin/* bin
    mv bin/init .

    file $(find .) | sort
    find . | cpio -o -H newc > ../initrd.img
cd ..
