#!/bin/bash

mkdir -p initrd
cd initrd
    mkdir -p bin

    cp ../src/bash bin

    cp ../src/busybox bin/
    cd bin
        for cmd in $(./busybox --list); do
            ln -s /bin/busybox $cmd || exit
        done
    cd ..

    cp -f ../SBinary/bin/* bin/
    mv bin/init .

    file $(find .) | sort
    find . | cpio -o -H newc > ../initrd.img
cd ..
