#!/bin/python3

tmp = ""

with open(".config", "r") as inputFile:
    for line in inputFile.readlines():
        tmp += line.replace("# CONFIG_STATIC is not set", "CONFIG_STATIC=y")

with open(".config", "w") as outputFile:
    outputFile.write(tmp)
