#!/bin/bash

KERNEL_VERSION_HEAD=6
KERNEL_VERSION=$KERNEL_VERSION_HEAD.4.10
KERNEL_ARCHIVE=linux-$KERNEL_VERSION.tar.xz

BUSYBOX_VERSION=1.36.1
BUSYBOX_ARCHIVE=busybox-$BUSYBOX_VERSION.tar.bz2

PACMAN_VERSION=6.0.2
PACMAN_ARCHIVE=pacman-$PACMAN_VERSION.tar.xz

if [ ! -f $KERNEL_ARCHIVE ]; then
    wget https://mirrors.edge.kernel.org/pub/linux/kernel/v$KERNEL_VERSION_HEAD.x/$KERNEL_ARCHIVE
fi

if [ ! -f $BUSYBOX_ARCHIVE ]; then
    wget https://busybox.net/downloads/$BUSYBOX_ARCHIVE
fi

if [ ! -f $PACMAN_ARCHIVE ]; then
    wget https://sources.archlinux.org/other/pacman/$PACMAN_ARCHIVE
fi

if [ "$1" = "kernel" ]; then
    mkdir -p src
    cd src
        rm -f -r linux-$KERNEL_VERSION
        tar -xf ../$KERNEL_ARCHIVE
        cd linux-$KERNEL_VERSION
            make defconfig
            make menuconfig
            make -j8 || exit
            cp arch/x86/boot/bzImage ../../
        cd ..
    cd ..
fi

if [ "$1" = "busybox" ]; then
    mkdir -p src
    cd src
        rm -f -r busybox-$BUSYBOX_VERSION busybox
        tar -xf ../$BUSYBOX_ARCHIVE
        cd busybox-$BUSYBOX_VERSION
            make defconfig
            ../../makeStatic
            make -j8 || exit
            cp busybox ../
        cd ..
    cd ..
fi

if [ "$1" = "pacman" ]; then
    mkdir -p src
    cd src
        rm -f -r pacman-$PACMAN_VERSION pacman pacman.conf
        tar -xf ../$PACMAN_ARCHIVE
        cd pacman-$PACMAN_VERSION
            meson build
            ninja -C build
            cp build/pacman ..
            cp build/pacman.conf ..
        cd ..
    cd ..
fi

mkdir -p SBinary
cd SBinary
    rm -f -r bin
    mkdir -p bin
    cd bin
        for script in $(find .. -name *.asm); do
            echo "Compiling $(basename $script)"
            nasm $script -o $(basename $script .asm).o -f elf64
            ld $(basename $script .asm).o -o $(basename $script .asm)
            rm -f $(basename $script .asm).o
        done
        for script in $(find .. -name *.cpp); do
            echo "Compiling $(basename $script)"
            g++ $script -o $(basename $script .cpp) -static || exit
        done
    cd ..
cd ..

rm -f -r initrd initrd.img
./makeInitrd
